### ISSUE TITLE
loqet create with no set context gives unhelpful error

### ISSUE THREAD

**Issue by JaceTSM** [JaceTSM/loqet#1]
To repro:
```
$ loqet context init play loqet/
$ loqet create passwords

Traceback (most recent call last):
  File "/mnt/d/github/play/bin/loqet", line 11, in <module>
    sys.exit(loqet_cli())
  File "/mnt/d/github/play/local/lib/python3.6/site-packages/loqet/loqet_cli.py", line 427, in loqet_cli
    loqet_command_router(args)
  File "/mnt/d/github/play/local/lib/python3.6/site-packages/loqet/loqet_cli.py", line 384, in loqet_command_router
    _, secret_key = get_context(args.context)
  File "/mnt/d/github/play/local/lib/python3.6/site-packages/loqet/loqet_contexts.py", line 277, in get_context
    loqet_keyfile = context_info["keyfile"]
TypeError: 'NoneType' object is not subscriptable
```

Solution:
Display helpful error when executing loqet commands with no active context set

**Comment by JaceTSM** [comment]
resolved in https://github.com/JaceTSM/loqet/commit/8b62c51e3c0d3d6f2bff895e18e3361572736586
